"""
Indicator Arena — CLI module.

Commands:
  emit <indicator_id>   — dry-run emit scaffold (pipeline integration point)
  review-due            — list signals past resolve_after that need review
  status                — show registry status summary
"""
from __future__ import annotations

import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import click

from .registry import get_active, get_by_id, load_registry, REGISTRY_PATH
from .signals import (
    SIGNALS_DIR,
    REQUIRED_FIELDS,
    _get_git_short_sha,
    read_signals,
)
from .reviews import REVIEWS_DIR, read_reviews
from .supabase_sync import sync_indicator_arena


# ---------------------------------------------------------------------------
# CLI group
# ---------------------------------------------------------------------------

@click.group(name="indicator-arena")
def cli() -> None:
    """Indicator Arena management commands."""


# ---------------------------------------------------------------------------
# emit
# ---------------------------------------------------------------------------

@cli.command()
@click.argument("indicator_id")
@click.option(
    "--dry-run",
    is_flag=True,
    default=False,
    help="Print the signal payload without writing to disk.",
)
@click.option(
    "--registry-path",
    default=None,
    help="Override path to registry.json (for testing).",
)
def emit(indicator_id: str, dry_run: bool, registry_path: str | None) -> None:
    """Emit a signal scaffold for INDICATOR_ID.

    In production the actual signal values are injected by the daily pipeline
    (scripts/indicator_arena_daily.py). This command validates that the
    indicator_id exists and prints the required field template.
    """
    reg_path = Path(registry_path) if registry_path else None
    spec = get_by_id(indicator_id, path=reg_path)
    if spec is None:
        click.echo(
            f"Error: unknown indicator_id '{indicator_id}'. "
            "Run 'indicator-arena status' to see valid IDs.",
            err=True,
        )
        sys.exit(1)

    if spec.status == "delisted":
        click.echo(
            f"Error: indicator '{indicator_id}' is delisted and cannot emit signals.",
            err=True,
        )
        sys.exit(1)

    now = datetime.now(timezone.utc).isoformat()
    scaffold: dict[str, Any] = {
        "signal_id": "<uuid — auto-generated by append_signal>",
        "indicator_id": indicator_id,
        "as_of_ts": f"<REQUIRED: data cutoff, must be ≤ {now}>",
        "emitted_at": now,
        "prediction": f"<REQUIRED: dict, e.g. {{direction: up}} for league={spec.league}>",
        "horizon_days": spec.horizon_days,
        "expires_at": "<REQUIRED: as_of_ts + horizon_days trading days, ISO UTC>",
        "data_hash": "<REQUIRED: sha256 of raw inputs dict>",
        "code_version": _get_git_short_sha(),
        "indicator_value": "<optional: raw numeric value>",
        "inputs_snapshot": "<optional: dict of input values used>",
    }
    if dry_run:
        click.echo("-- DRY RUN: signal scaffold (not written) --")
        click.echo(json.dumps(scaffold, indent=2, ensure_ascii=False))
    else:
        click.echo(json.dumps(scaffold, indent=2, ensure_ascii=False))


# ---------------------------------------------------------------------------
# review-due
# ---------------------------------------------------------------------------

@cli.command(name="review-due")
@click.option(
    "--signals-dir",
    default=None,
    help="Override path to signals/ directory.",
)
@click.option(
    "--reviews-dir",
    default=None,
    help="Override path to reviews/ directory.",
)
def review_due(signals_dir: str | None, reviews_dir: str | None) -> None:
    """List signals whose resolve_after time has passed but have no review yet."""
    sig_dir = Path(signals_dir) if signals_dir else SIGNALS_DIR
    rev_dir = Path(reviews_dir) if reviews_dir else REVIEWS_DIR

    now = datetime.now(timezone.utc)

    # Collect all signals from all JSONL files
    all_signals: list[dict[str, Any]] = []
    if sig_dir.exists():
        for f in sorted(sig_dir.glob("*.jsonl")):
            year_month = f.stem
            all_signals.extend(read_signals(year_month, sig_dir))

    # Collect all reviewed signal_ids
    reviewed_ids: set[str] = set()
    if rev_dir.exists():
        for f in sorted(rev_dir.glob("*.jsonl")):
            year_month = f.stem
            for row in read_reviews(year_month, rev_dir):
                reviewed_ids.add(row.get("signal_id", ""))

    # Find due-but-unreviewed
    due: list[dict[str, Any]] = []
    for sig in all_signals:
        sid = sig.get("signal_id", "")
        if sid in reviewed_ids:
            continue
        resolve_after = sig.get("resolve_after")
        if resolve_after:
            try:
                resolve_dt = datetime.fromisoformat(
                    resolve_after.replace("Z", "+00:00")
                )
                if now >= resolve_dt:
                    due.append(sig)
            except (ValueError, TypeError):
                pass
        else:
            # No resolve_after set — treat as immediately due
            due.append(sig)

    if not due:
        click.echo("No signals due for review.")
        return

    click.echo(f"Signals due for review ({len(due)}):")
    for sig in due:
        click.echo(
            f"  {sig.get('signal_id', '?')} | {sig.get('indicator_id', '?')} "
            f"| as_of={sig.get('as_of_ts', '?')} "
            f"| resolve_after={sig.get('resolve_after', 'N/A')}"
        )


# ---------------------------------------------------------------------------
# status
# ---------------------------------------------------------------------------

@cli.command()
@click.option(
    "--registry-path",
    default=None,
    help="Override path to registry.json.",
)
@click.option(
    "--json-output",
    is_flag=True,
    default=False,
    help="Output as JSON.",
)
def status(registry_path: str | None, json_output: bool) -> None:
    """Show indicator registry status summary."""
    reg_path = Path(registry_path) if registry_path else None
    try:
        all_specs = load_registry(reg_path)
    except FileNotFoundError as exc:
        click.echo(f"Error: {exc}", err=True)
        sys.exit(1)

    counts: dict[str, int] = {"active": 0, "observation": 0, "delisted": 0}
    rows = []
    for spec in all_specs:
        counts[spec.status] = counts.get(spec.status, 0) + 1
        rows.append(
            {
                "indicator_id": spec.indicator_id,
                "name_zh": spec.name_zh,
                "league": spec.league,
                "status": spec.status,
                "horizon_days": spec.horizon_days,
                "k_refs": spec.k_refs,
            }
        )

    if json_output:
        click.echo(
            json.dumps(
                {"summary": counts, "indicators": rows},
                indent=2,
                ensure_ascii=False,
            )
        )
    else:
        click.echo(
            f"Indicator Arena — {counts['active']} active, "
            f"{counts['observation']} observation, "
            f"{counts['delisted']} delisted "
            f"(total {len(all_specs)})"
        )
        for row in rows:
            click.echo(
                f"  [{row['status'].upper():<11}] {row['indicator_id']:<35} "
                f"league={row['league']:<13} horizon={row['horizon_days']}d "
                f"k_refs={row['k_refs']}"
            )


@cli.command(name="sync-supabase")
@click.option(
    "--storage-dir",
    default="storage",
    show_default=True,
    help="Local storage root containing indicator_arena/.",
)
@click.option(
    "--dry-run",
    is_flag=True,
    default=False,
    help="Show counts + preview without invoking Supabase.",
)
def sync_supabase(storage_dir: str, dry_run: bool) -> None:
    """Project local indicator_arena canonical files into Supabase tables."""
    click.echo(json.dumps(sync_indicator_arena(storage_dir=storage_dir, dry_run=dry_run), indent=2, ensure_ascii=False))


if __name__ == "__main__":
    cli()
