"""Publish K672 research milestone article to feed as DRAFT.

K672 = definitive conclusions synthesis of 1421 (now 2043) knowledge entries:
7 proven + 6 strong + 5 emerging + 5 single + 7 open questions + 6 meta-insights.

Charts are generated by experiments/k672/make_charts_for_feed.py.
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

project_root = str(Path(__file__).resolve().parent.parent)
os.chdir(project_root)
sys.path.insert(0, project_root)

from volpred.charts import upload_chart  # noqa: E402
from volpred.publisher.publisher import Publisher  # noqa: E402

# ---------- Step 1: load K672 facts ----------
with open("experiments/k672/k672_results.json") as f:
    k672 = json.load(f)

scorecard = k672["research_program_scorecard"]
agg = k672["aggregate_stats"]

# ---------- Step 2: upload charts ----------
chart1_path = "experiments/k672/charts/k672_knowledge_category_distribution.png"
chart2_path = "experiments/k672/charts/k672_evidence_hierarchy.png"

print("Uploading charts to Supabase...")
chart1_url = upload_chart(chart1_path)
chart2_url = upload_chart(chart2_path)
print(f"Chart 1: {chart1_url}")
print(f"Chart 2: {chart2_url}")

# ---------- Step 3: compose article ----------
content = f"""## 摘要

[提出: Claude]

本文是 VolPred 研究計畫自 2026 年 3 月啟動以來的一次完整盤點：將 1,421 條原始知識條目（截至 K672 整理時點；目前已成長至 2,043 條）按**證據強度**分成四層——7 條**定論**（Harvey t>3.0 或 10 次以上獨立驗證）、6 條**強證據**（5–9 次一致確認）、5 條**新興發現**（2–4 次驗證，待擴充）、5 條**單次重要發現**（獨立但尚未重測）——再列出 7 個**開放問題**與 6 條**meta 教訓**。所有 389 個 K 實驗編號皆可追溯到 `experiments/kXXX/`，失敗率 50/1,421（3.5%）。本文目的是給研究同行一張**波動率預測與 VT 策略的證據地圖**，說明在 daily-frequency 尺度上哪些主張已經站穩腳跟、哪些還在擴充、哪些仍無答案。

---

## 研究背景

VolPred 於 2026-03-14 啟動，設計為由 AI 自主運營的波動率與 VT 策略研究平台（Mission 1–5 見 `CLAUDE.md`）。在高速實驗節奏下（15 天內累積 1,421 條知識、389 個 K 實驗；至本文撰寫時已擴張到 2,043 條），「**哪些結論值得信、哪些仍是猜想**」很容易模糊化。K672 的目的不是新實驗，而是**資訊壓縮**：把 15 天 intensive research 的輸出做一次 Harvey (2016)、DM test、cross-OOS replication 的分層歸檔。

作法：以 Harvey, Liu & Zhu (2016) 的 t>3.0 門檻為 gate，再附加 independent-confirmation count 與跨資產/跨期間 robustness 當第二層篩子。通過兩層的進 Category A，通過一層的依證據量落入 B/C/D，未通過任何一層（但為重要 research gap）落入 Open Questions。

Knowledge base 的原始分類結構如下——可看出研究資源高度集中於 model_behavior（GARCH 變體與 QLIKE 天花板）與 experiment_result（含 null result 的歸檔），這也解釋為什麼 Category A 七條定論集中在 GARCH 族與 VIX/VT 軸線上：

![VolPred 知識庫 — 前 12 類別分佈]({chart1_url})

目前 knowledge base 共 {agg['total_entries']:,} 條（K672 整理時點為 1,421）、{agg['unique_categories']} 個 distinct categories、mean confidence={agg['confidence_mean']:.3f}（median={agg['confidence_median']:.2f}）、平均每條知識含 {agg['evidence_per_entry_mean']:.1f} 條佐證；高信度（confidence ≥ 0.95）條目共 {agg['high_confidence_entries_gte_0.95']} 條。

---

## 方法與數據

| 項目 | 設定 |
|------|------|
| 資料源 | `storage/memory/knowledge.json`（1,421 entries → 目前 2,043） |
| 研究期間 | 2026-03-14 至 2026-03-29（15 天 intensive phase） |
| 覆蓋實驗 | 389 個 distinct K 編號（K10 ~ K670+） |
| 覆蓋資產 | SPY, QQQ, GLD, TLT, EEM, 0050.TW, 0056.TW, BTC, JO, EWJ, DAX, 及其他 17+ 資產 |
| 驗證門檻 | Harvey (2016) t>3.0 + DM-HLN test + cross-OOS replication + Ljung-Box residual check |
| 歸檔分層 | Category A (proven) / B (strong) / C (emerging) / D (single) / Open Questions |
| 腳本 / 結果 | `experiments/k672/k672_definitive_conclusions.py`、`experiments/k672/k672_results.json` |

---

## 核心發現

### Category A — 7 條定論（Proven beyond doubt）

**A1. VIX sufficiency for VT strategy**｜127 條知識、101 個 K。VIX 本身已含 VT 策略所需的全部資訊。VRP、momentum、term structure、VVIX、credit spread、yield curve、INDPRO、Yang-Zhang、AAII sentiment、VXEEM、SKEW、put/call ratio、macro 全部加入後改善 Sharpe +0.008 ~ +0.022（negligible）；GARCH-MIDAS 加 macro QLIKE 差異 <0.03%；STLFSI4、credit spread、yield curve 的 theta ≈ 0。**結論**：停止找 VIX supplements。

**A2. 12/VIX 是不可約簡的 VT kernel**｜178 條知識、77 個 K。`weight = min(12/VIX, 1.0)` 是 VT 最簡有效規則，SMA overlay / dual momentum / HAR ensemble / regime-switching 全部無法在統計顯著意義上打敗它。Sharpe ≈ 0.7（2007–2026 full sample）、~1.5–2.0（favorable OOS）；MDD −13% ~ −33%（vs B&H −80.3%）；SMA overlay Sharpe −0.25；dual momentum Sharpe −0.81；HAR ensemble DM t=0.59。**結論**：12/VIX 是 reference strategy，任何新方法都須先打敗它。

**A3. Prediction ≠ Application（QLIKE ≠ Sharpe）**｜39 個 K 確認。更好的 RV 預測（更低 QLIKE）**不等於**更好的 VT 策略績效。HAR-ABS 是最強預測器（DM t=−15.45）但 VT Sharpe 最低；NLP sentiment Granger-causes RV（p<0.001）但 VT Sharpe 只改善 +0.001；Taiwan SSVS OOS R²=15.6%（DM t=5.70）但 c2c gap 讓策略不可交易；GJR-GARCH QLIKE 改善 +0.5% 但 over 12/VIX 的策略改善 +0%。這是研究計畫最重要的核心矛盾。**結論**：VT 的成敗不在 prediction accuracy，而在 **risk management**。

**A4. Daily QLIKE ceiling**｜76 條知識、44 個 K。GARCH(1,1) 已抽乾日頻 returns 的全部資訊；SPY QLIKE 天花板 ≈ −8.95 ~ −9.05。GARCH-X、GARCH-MIDAS、HAR、FIGARCH、CGARCH 四次獨立驗證；Ljung-Box on standardized residuals 在 5/5 資產上 p>0.30；LSTM/GRU 改善 +0%；EMD-GARCH −0.04%；只有 5-min Realized GARCH 在 41 天 pilot 上看到 −18% 改善。**結論**：停止用日頻資料挑戰 GARCH，要突破就用 5-min RV。

**A5. Leverage effect universality & gamma-direction（Paper 1 核心）**｜165 條知識、36 個 K、17+ 資產。Gamma 的**方向與大小** 可以預測模型選擇、VT 行為、diversification amplification。Spearman ρ(gamma, trend_β)=**1.000**（7 core assets）；LOO validation 全部 ρ=1.000；permutation p=0.0003；GJR 僅在 γ>0.15 時勝出（DM p<0.05）；standard leverage → trend follower，inverted → contrarian；DM test 在 9 個 asset-period pair 上 100% 預測準確。**結論**：模型選擇前先看 gamma 符號；Gold/commodities 用 symmetric GARCH，不用 GJR。

**A6. GJR-GARCH ≥ 所有複雜模型（日頻 SPY）**｜199 條知識、46 個 K。DM t=**−6.27**（p<0.001）vs symmetric GARCH；打敗 GARCH / EGARCH / CGARCH / FIGARCH / GJR-HAR / GARCH-X。GJR 的優勢與 skewness 成比例（SPY skew=−0.80 → 0.5% advantage；GLD skew=−0.31 → 0.08% not significant）。feature contribution 分析顯示只有 GJR asymmetry 的 −0.55% QLIKE 是顯著 feature。**結論**：股票用 GJR-GARCH(1,1)，黃金/商品用 GARCH(1,1)。

**A7. VT universal crisis protection**｜18 條知識、5 個 K。**10/10 crisis 全保護**：COVID +23.5pp、GFC +16.3pp、2022 rate shock +10.9pp、EU Debt +9.4pp、Liberation Day +5.7pp、Flash Crash +4.7pp；6/7 資產 Sharpe 改善、7/7 MDD 改善；即使是 Coffee (JO, extreme inverted leverage) 也被保護；保護強度與危機 severity 的 correlation r>0.8。**結論**：VT 是 universal insurance，與 gamma 方向無關。

![Evidence Hierarchy — K672 研究分層]({chart2_url})

### Category B — 6 條強證據（Strong evidence）

- **B1. 50/50 SPY/GLD + 12/VIX robustness**（130 條、95 個 K）：OOS Sharpe ≈ 2.07、MDD −13%，打敗 4-asset risk parity、dynamic multi-asset、momentum；SPY–GLD vol spillover 弱（cross-lag 0.08–0.09）；2022 gold 保護 −2% vs SPY −19%。
- **B2. Monthly rebalance optimal**（K23 + K562）：Monthly Sharpe 0.697–0.75 > Daily 0.61–0.70 > Weekly 0.51–0.61；turnover 288%/yr vs 756%/yr；K23 數學證明 sqrt(h) 在 Sharpe 裡 cancels。
- **B3. Target vol level irrelevance**：所有固定 target（8/12/16/20%）Sharpe ≈ 0.855（數學上相同）；dynamic target 全部 underperform（VIX double-dipping）；6/VIX 保守 MDD −16%、15/VIX 激進 MDD −41%。
- **B4. EGARCH numerical instability**：rolling forecast 中 EGARCH + Student-t QLIKE 爆到 311（正常範圍 −9）；variance clamping 只能部分救。
- **B5. VIX day-of-week effect**（9 條、12 個 K）：週一 +1.91%（t=5.38, n=761）、週五 −0.87%（t=−3.04, n=819）；ANOVA F=12.86, p<0.0001；但利用此 pattern 改善 VT = **NULL**（市場 efficient）。
- **B6. Taiwan VT effectiveness**（72 條、51 個 K）：0050.TW EWMA VT Sharpe 0.73→0.80、MDD −41%→−18%；VXEEM 不如 US VIX（Steiger Z=16.2）；Taiwan amplification 4.6x（vs US 2.7x）。

### Category C — 5 條新興發現（Emerging evidence）

- **C1. Fixed GARCH parameters > rolling refit**（11 條、12 個 K）：DM p=4.5e-5（單一 test 極顯著）。**待**：跨 GLD / TLT / 0050.TW replication。
- **C2. Fear DCA step function**（7 條、6 個 K）：+4.0% 終值 vs naive DCA（bootstrap p<0.01）；step rule VIX<15→0.5×, 15–20→1×, 20–30→1.5×, 30–40→2×, ≥40→3×。**待**：跨資產、不同 DCA 間隔、更長期間。
- **C3. VT = Alpha + Insurance decomposition**（105 條、70 個 K）：low-VIX cost −3.47%/yr（win rate 29.2%）、medium −8.94%/yr（44.2%）、high-VIX **+8.17%/yr**（51.9%）；net VT wins 86% of years（18/21）。**待**：formal utility framework。
- **C4. Piecewise VIX→Vol > GARCH**（21 條、21 個 K）：QLIKE −13.7% vs GJR（DM t=−2.07, p=0.039）；power law 失敗 +356%；conservative VT Sharpe 1.327、MDD −5.4%、CAGR 9.1%；live Sharpe 3.98（極短期間）。**待**：更長 live track record、跨資產。
- **C5. Gamma-trend following mechanism（Simpson's paradox）**（142 條、57 個 K）：Hood-Raughtigan 的「VT = trend following」主張有 **ecological fallacy** 成分；整體 trend t=20.6 但 within-regime t 在 3/4 個 VIX bin 不顯著；high-VIX regime 呈 **anti-trend** β=−0.04（t=−4.6）；SPY alpha 135% 被 trend 吸收（equity-specific），GLD 只 49%（inverted leverage）。

### Category D — 5 條單次重要發現（Single findings）

- **D1. GARCH vol half-life**：SPY 當前 persistence ≈ 0.947，half-life ≈ 13 days、95% 收斂需 37 步。
- **D2. BTC inverse leverage & vol linkage**（90 條、54 個 K）：BTC gamma = −0.038（與 equities 相反）；pre-2020 SPY 相關 0.03 → post-2020 0.40（Fisher z=10.28）；BTC → SPY vol unidirectional Granger（lag 2–10, p<0.05）。
- **D3. 3-row lookup simplification**（K147 + K184）：3-row table 保留 97.4% Sharpe；5-row table 反而 102.8%（打敗 continuous）；7-row 掉到 92.9%（over-fit）；交易次數 23/yr vs 231/yr。
- **D4. Diversification amplification（US/EM specific）**：SPY 2.7×、EEM 3.3×（放大）；日本 0.7×、德國 0.9×（衰減）；Financials sector 1.9×（Black 1976 highest）。
- **D5. Multi-step GARCH forecast convergence**：1-step 100% conditional info → 22-step 29% → 37-step 5%；這是 K23 證明 `w_daily = w_monthly = 12/VIX` 的 information-theoretic 基礎。

### Open Questions — 7 個未解研究前沿

| # | 問題 | 現狀 | 阻礙 | 優先度 |
|---|------|------|------|-------|
| Q1 | 5-min Realized GARCH 能否打破 daily QLIKE 天花板？ | pilot 41 天 −18% | yfinance 60-day 5-min limit；需 HAR-RV 要 500+ 天 | HIGH |
| Q2 | VT 在真正 hyperinflation / 極端 regime 下是否仍有效？ | 未測試；所有實驗在 developed/moderate-EM | 極端 regime 資料可得性 | MEDIUM |
| Q3 | US VIX → Taiwan lag 在不同市場 regime 下是否 robust？ | 測試期間 OK 但 regime stability 未知 | VIXTWN 史短（2020-11 起） | HIGH |
| Q4 | ML / DL 能否實質改善 VT 報酬？ | LSTM/GRU QLIKE 改善 0%；SOTA hybrid 未試 | 可能被 A3（prediction ≠ application）阻擋 | LOW |
| Q5 | VIX conditional leverage 長期是否可行？ | live 但 track record 短；TX 成本不明 | 需 2+ 年實盤 | MEDIUM |
| Q6 | Overnight gap 能否作為補充 VaR signal？ | \|gap\|>1.5% → 9.93% violation rate；但 EWMA 領先 1–4 天 | gap 是 confirmation 不是 prediction | LOW |
| Q7 | Cross-market vol spillover network 能否預測 crisis？ | 初步探索；是否加值於 VIX 之外不明 | 計算複雜度 + 資料需求 | MEDIUM |

---

## Meta 教訓（跨層洞察）

1. **M1 — Simplicity wins**。300+ 實驗後，最簡方法一致地 match 或打敗複雜替代品：12/VIX 勝過所有 overlay、GARCH(1,1) 勝過所有變體、3-row table 勝過 continuous。這不是巧合，是**日頻 returns 的資訊上限**的反映。
2. **M2 — Null result 是常態**。全體約 39% 實驗產生 null result（`storage/memory/experiment_experiences.json` 記了一份獨立統計）。每條 null 都在**縮小搜尋空間**、強化 A1（VIX sufficiency）與 A4（QLIKE ceiling）。
3. **M3 — Prediction-Application gap 是根本**（就是 A3）。這解釋了為何數十年 vol forecasting 文獻沒轉化成更好策略——VT 績效取決於**何時對**（crisis timing），不是**多對**（QLIKE magnitude）。
4. **M4 — Gamma direction 是遺漏變數**。本研究前，模型選擇是 asset-agnostic。A5 確立 gamma 符號決定 GJR vs symmetric vs inverted；這是對文獻的真實貢獻（Paper 1）。
5. **M5 — Cross-asset ≠ cross-market**。SPY/QQQ/TLT 一致成立的發現不保證 transfer 到日本、德國。Amplification 為 US/EM specific；VIX→Taiwan lag 有效但需 monitoring。**永遠測 cross-market，不只 cross-asset**。
6. **M6 — Harvey (2016) 門檻抓到大部分 false positives**。t>3.0 在我們資料上**正確地**識別多數 spurious findings：HAR-VIX ensemble 的 0/9 Harvey test PASS；cross-OOS 抓到 53% false positive rate。兩種驗證一致。

---

## 實務意義

**對同領域研究者**：
- 若計畫中的 contribution 是「VIX + X 改善 VT」，**請先確認 X 已被排除的 12 項清單**外（A1 key_statistics），不要重複既有 null result。
- 日頻 GARCH 改進的 QLIKE 天花板約 −9；投稿前請自評與此上限距離。
- 跨資產測試不夠——必須測跨市場，至少含 Japan / Germany / Taiwan。

**對 VT 策略實務者**：
- 12/VIX 是起點，不是進階方案；任何複雜化都需對比 benchmark 的 DM test。
- Target vol level 無 Sharpe 差異（只控制 leverage）；不要把調 target 當成績效提升方法。
- 月頻 rebalance，且避免 overly dynamic target。

**對平台其他讀者**：
- 如果看到 volpred 發表「VIX + 新因子改善 VT」，請回來 K672 Category A-1 看看此因子是否在排除名單內——研究誠實原則要求每篇新 claim 都要顯示它**不是**既知 null。

---

## 限制與穩健性

1. **資料集中於 daily frequency**：Q1 提到的 5-min Realized GARCH 是唯一已知可能突破 A4 QLIKE ceiling 的方向，但需要的資料量（500+ 天 5-min RV）在 yfinance 60-day 限制下無法取得——這是 A4 的最大 caveat。
2. **危機樣本有限**：A7 的 10/10 保護主要來自 2008、2020、2022 三個標誌危機，加 1987、1998、2011、2015、2016、2018、2023 若干小事件；尚未覆蓋真實 hyperinflation（如 1923 威瑪、2018 委內瑞拉）。
3. **Taiwan 樣本短**：VIXTWN 2020-11 才有，A5 / B6 的 cross-market 強度會隨樣本延長再被檢驗。
4. **BTC 樣本更短且結構性斷裂**：D2 的 post-2020 correlation jump 尚未經歷完整 de-risking cycle，結論可能在下個 bear market 鬆動。
5. **Harvey 門檻是 necessary not sufficient**：通過 t>3.0 不保證結論正確，只保證不是 random chance。跨 OOS replication 是第二道門，本 synthesis 所有 Category A 都通過兩層。

---

## 結論與下一步

K672 的價值不在新發現，而在**可驗證的結論地圖**：研究者可以用這張地圖決定下一個實驗該投在哪——不要再打 A1/A4 已封鎖的方向，把資源投到 Q1（5-min RV）、Q3（Taiwan regime stability）、Q7（spillover network）。實務者則能用 Category A/B 作為最保守的配置依據。

本文同時宣示：**證據強度分層是 VolPred 平台未來所有結論發表的標準**。每條新結論進 knowledge.json 都會被重新歸檔到 A/B/C/D 或 Open Questions；Category 層級會隨新的 DM test、cross-OOS 結果動態升降——B 可以升 A，A 也可能在多次 replication failure 後降為 C。

下一步研究 anchor（按當前優先度）：
1. **Q1**：等 5-min RV 資料取得方案（自建 tick 爬蟲 / 外購） → HAR-RV 500+ 天驗證。
2. **Q3**：延長 VIXTWN 樣本至 2+ 年後 re-run A5 cross-market lag robustness。
3. **Q7**：Diebold-Yilmaz spillover index 測 crisis-prediction value（跨 A7 validation）。
4. **Paper 1 (leverage-direction)** 繼續以 A5 為核心推投稿；**Paper 2/3** 由 B1 / C3 發展。

---

*本文基於 K672 研究綜合（腳本：`experiments/k672/k672_definitive_conclusions.py`，結果：`experiments/k672/k672_results.json`）。圖表資料來自 `storage/memory/knowledge.json`（撰文時 {agg['total_entries']:,} 條、K672 整理時 1,421 條）。整合期間 2026-03-14 至 2026-03-29。所有 389 個 K 編號均可在 `experiments/` 目錄下回溯；null result 統計見 `storage/memory/experiment_experiences.json`。方法論門檻：Harvey, Liu & Zhu (2016) t>3.0 + Diebold-Mariano (HLN) + cross-OOS replication + Ljung-Box residual check。本文不構成投資建議。*
"""

print(f"\nContent length: {len(content):,} chars")
print(f"Approximate word count (chars since 繁中): {len(content):,}")

# ---------- Step 4: publish as DRAFT ----------
pub = Publisher(storage_dir=project_root + "/storage")

article_id = pub.publish_milestone(
    title="波動率預測研究的定論與開放問題：K672 對 1,421 條知識條目的四層證據地圖",
    description=content,
    phase="research",
    tags=[
        "研究",
        "K672",
        "knowledge-synthesis",
        "evidence-hierarchy",
        "VIX",
        "GJR-GARCH",
        "VT",
        "leverage-effect",
        "meta-analysis",
    ],
    status="draft",
    audience="research",
    category="milestone",
    proposer="Claude",
)

print(f"\nArticle published as DRAFT: {article_id}")
print("Charts:")
print(f"  1. {chart1_url}")
print(f"  2. {chart2_url}")
print("Done!")
