#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import subprocess
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any
from zoneinfo import ZoneInfo
import fcntl

ROOT = Path(__file__).resolve().parents[1]
STORAGE = ROOT / "storage"
OPS = STORAGE / "ops"
NEXT_TASKS = STORAGE / "next_tasks.json"
STATE_PATH = OPS / "daily_reader_facing_scan_state.json"
TRENDING_LOG = STORAGE / "reports" / "trending_repost_log.json"
RUNTIME_SCHEDULES = ROOT / "config" / "runtime_schedules.json"
LOCAL_TZ = ZoneInfo("Asia/Taipei")
TRENDING_SCAN_CMD_ENV = "VOLPRED_TRENDING_SCAN_CMD"


def _now_utc() -> datetime:
    return datetime.now(timezone.utc)


def _now_local() -> datetime:
    return _now_utc().astimezone(LOCAL_TZ)


def _today_local() -> str:
    return _now_local().date().isoformat()


def _warn_refill_reader(message: str, path: Path, exc: Exception) -> None:
    print(
        f"[reader_facing_refill] WARN {message}: "
        f"path={path} error={type(exc).__name__}: {exc}"
    )


def _load_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:
        _warn_refill_reader("JSON read failed; using default", path, exc)
        return default


def _write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def _load_next_tasks() -> list[dict[str, Any]]:
    return _load_json(NEXT_TASKS, [])


def _append_task(task: dict[str, Any]) -> bool:
    NEXT_TASKS.parent.mkdir(parents=True, exist_ok=True)
    if not NEXT_TASKS.exists():
        NEXT_TASKS.write_text("[]\n", encoding="utf-8")
    with NEXT_TASKS.open("r+", encoding="utf-8") as fh:
        fcntl.flock(fh.fileno(), fcntl.LOCK_EX)
        try:
            data = json.load(fh)
            if not isinstance(data, list):
                raise ValueError("next_tasks.json is not a list")
            if any(isinstance(item, dict) and item.get("id") == task["id"] for item in data):
                return False
            data.append(task)
            fh.seek(0)
            fh.truncate()
            json.dump(data, fh, ensure_ascii=False, indent=2)
            fh.write("\n")
            return True
        finally:
            fcntl.flock(fh.fileno(), fcntl.LOCK_UN)


def _load_runtime_event_items() -> list[dict[str, Any]]:
    payload = _load_json(RUNTIME_SCHEDULES, {})
    event_jobs = payload.get("event_jobs") if isinstance(payload, dict) else None
    items = event_jobs.get("items") if isinstance(event_jobs, dict) else None
    return items if isinstance(items, list) else []


def _task_exists(task_id: str) -> bool:
    tasks = _load_next_tasks()
    return any(isinstance(item, dict) and item.get("id") == task_id for item in tasks)


def _event_task_id(event_type: str, event_date: str, slot: str) -> str:
    slot_norm = slot.lower().replace("+", "plus").replace("-", "minus")
    return f"event_article_{event_type.lower()}_{event_date}_{slot_norm}"


def _build_event_task(item: dict[str, Any]) -> dict[str, Any]:
    payload_patch = ((item.get("task_template") or {}).get("payload_patch") or {})
    event_type = str(payload_patch.get("event_type") or item.get("event_key") or "event").lower()
    event_date = str(payload_patch.get("event_date") or "unknown-date")
    slot = str(payload_patch.get("event_series_slot") or "T-0")
    title = str((item.get("task_template") or {}).get("title") or item.get("id") or "event article")
    description = str((item.get("task_template") or {}).get("description") or "")
    return {
        "id": _event_task_id(event_type, event_date, slot),
        "title": f"[event_article] {title}",
        "description": (
            f"Auto-generated by refill_reader_facing_pool.py from event_jobs.\n"
            f"ref_event_job_id: {item.get('id')}\n"
            f"event_key: {item.get('event_key')}\n"
            f"event_type: {event_type}\n"
            f"event_date: {event_date}\n"
            f"event_series_slot: {slot}\n\n"
            f"{description}"
        ),
        "task_type": "event_article",
        "priority": 1,
        "status": "pending",
        "created_at": _now_utc().isoformat(timespec="seconds"),
        "source": "reader_facing_refill",
        "ref_event_job_id": item.get("id"),
        "event_key": item.get("event_key"),
        "event_type": event_type,
        "event_date": event_date,
        "event_series_slot": slot,
        "tags": ["event_article", "reader_facing", event_type, slot],
    }


def refill_event_candidates(*, horizon_days: int = 14) -> dict[str, Any]:
    now = _now_utc()
    added: list[str] = []
    skipped: list[dict[str, str]] = []
    for item in _load_runtime_event_items():
        payload_patch = ((item.get("task_template") or {}).get("payload_patch") or {})
        event_date_raw = payload_patch.get("event_date")
        if not event_date_raw:
            skipped.append({"id": str(item.get("id")), "reason": "missing_event_date"})
            continue
        try:
            event_date = datetime.fromisoformat(str(event_date_raw)).date()
        except ValueError as exc:
            _warn_refill_reader(
                f"event_date parse failed; skipping event item id={item.get('id')} raw={event_date_raw!r}",
                RUNTIME_SCHEDULES,
                exc,
            )
            skipped.append({"id": str(item.get("id")), "reason": "bad_event_date"})
            continue
        delta_days = (event_date - now.astimezone(LOCAL_TZ).date()).days
        if delta_days < 0 or delta_days > horizon_days:
            skipped.append({"id": str(item.get("id")), "reason": "out_of_horizon"})
            continue
        not_before_raw = item.get("not_before")
        if not_before_raw:
            try:
                not_before_dt = datetime.fromisoformat(str(not_before_raw))
            except ValueError as exc:
                _warn_refill_reader(
                    f"not_before parse failed; skipping event item id={item.get('id')} raw={not_before_raw!r}",
                    RUNTIME_SCHEDULES,
                    exc,
                )
                skipped.append({"id": str(item.get("id")), "reason": "bad_not_before"})
                continue
            if not_before_dt is not None:
                if not_before_dt.tzinfo is None:
                    not_before_dt = not_before_dt.replace(tzinfo=LOCAL_TZ)
                if now < not_before_dt.astimezone(timezone.utc):
                    skipped.append({"id": str(item.get("id")), "reason": "not_yet_in_window"})
                    continue
        task = _build_event_task(item)
        if _append_task(task):
            added.append(task["id"])
        else:
            skipped.append({"id": task["id"], "reason": "already_exists"})
    return {"added": added, "skipped": skipped}


def refill_member_qa() -> dict[str, Any]:
    try:
        import sys

        sys.path.insert(0, str(ROOT / "src"))
        from volpred.ops.questions import ensure_member_qa_task

        result = ensure_member_qa_task(source="user")
        return {"ok": True, "result": result}
    except Exception as exc:
        return {"ok": False, "error": repr(exc)}


def _extract_trending_candidates(payload: Any) -> list[dict[str, Any]]:
    if isinstance(payload, list):
        return [item for item in payload if isinstance(item, dict)]
    if isinstance(payload, dict):
        items = payload.get("candidates")
        if isinstance(items, list):
            return [item for item in items if isinstance(item, dict)]
    return []


def _build_trending_task(candidate: dict[str, Any]) -> dict[str, Any]:
    task_id = str(candidate.get("id") or "").strip()
    if not task_id:
        topic = str(candidate.get("topic") or "trending")
        task_id = f"trending_repost_{_today_local().replace('-', '_')}_{topic.lower().replace(' ', '_')[:40]}"
    title = str(candidate.get("title") or candidate.get("topic") or "trending repost candidate")
    description = str(candidate.get("description") or candidate.get("brief") or "")
    return {
        "id": task_id,
        "title": f"[trending_repost] {title}",
        "description": description,
        "task_type": "trending_repost",
        "priority": 1,
        "status": "pending",
        "created_at": _now_utc().isoformat(timespec="seconds"),
        "source": "reader_facing_refill",
        "tags": ["trending_repost", "reader_facing", "auto_refill"],
    }


def refill_trending_candidates() -> dict[str, Any]:
    cmd = os.environ.get(TRENDING_SCAN_CMD_ENV, "").strip()
    if not cmd:
        # Trending scan is best-effort: main pipeline relies on the trending_repost
        # agent doing WebSearch itself. Missing scan command is a skip, not an error.
        return {
            "ok": True,
            "skipped": True,
            "reason": "no_scan_cmd_configured",
            "hint": f"set {TRENDING_SCAN_CMD_ENV} to enable batch refill",
            "added": [],
        }
    proc = subprocess.run(cmd, shell=True, capture_output=True, text=True, cwd=ROOT)
    if proc.returncode != 0:
        return {"ok": False, "reason": "scan_failed", "stderr": proc.stderr[-500:]}
    try:
        payload = json.loads(proc.stdout or "[]")
    except json.JSONDecodeError as exc:
        return {"ok": False, "reason": "bad_json", "error": str(exc)}

    added: list[str] = []
    skipped: list[dict[str, str]] = []
    for candidate in _extract_trending_candidates(payload)[:1]:
        task = _build_trending_task(candidate)
        if _append_task(task):
            added.append(task["id"])
        else:
            skipped.append({"id": task["id"], "reason": "already_exists"})
    return {"ok": True, "added": added, "skipped": skipped}


def _default_state() -> dict[str, Any]:
    return {
        "date": _today_local(),
        "scanned": False,
        "scanned_at": None,
        "trending_added": 0,
        "event_added": 0,
        "member_qa_added": 0,
        "errors": [],
    }


def run_refill(*, force: bool = False) -> dict[str, Any]:
    state = _load_json(STATE_PATH, _default_state())
    today = _today_local()
    if not force and state.get("date") == today and state.get("scanned") is True:
        return {
            "skip": True,
            "reason": "already_scanned_today",
            "state": state,
        }

    result = _default_state()
    result["scanned_at"] = _now_utc().isoformat(timespec="seconds")

    trending = refill_trending_candidates()
    if trending.get("ok"):
        result["trending_added"] = len(trending.get("added") or [])
        if trending.get("skipped"):
            result["trending_skipped"] = {
                "reason": trending.get("reason"),
                "hint": trending.get("hint"),
            }
    else:
        result["errors"].append({"source": "trending_scan", **trending})

    events = refill_event_candidates()
    result["event_added"] = len(events.get("added") or [])
    if events.get("skipped"):
        result["event_skipped"] = events["skipped"][:20]

    member = refill_member_qa()
    if member.get("ok") and isinstance(member.get("result"), dict) and member["result"].get("created"):
        result["member_qa_added"] = 1
    elif not member.get("ok"):
        result["errors"].append({"source": "member_qa_eval", **member})
    else:
        result["member_qa_result"] = member.get("result")

    result["scanned"] = True
    _write_json(STATE_PATH, result)
    return {"skip": False, "state": result}


def main() -> int:
    parser = argparse.ArgumentParser(description="Refill reader-facing task pool (event/trending/member_qa)")
    parser.add_argument("--force", action="store_true", help="Ignore daily state and scan again")
    args = parser.parse_args()

    outcome = run_refill(force=args.force)
    print(json.dumps(outcome, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
