#!/usr/bin/env python3
"""PreToolUse(Edit|Write): refuse to overwrite gate bytes that exist nowhere else.

THE BUG CLASS (K1708, 2026-07)
------------------------------
K1708 failed Codex primary-path review three rounds running. One of its two root
causes was not a bug in the experiment at all -- it was a bug in *when* evidence
gets saved:

  The verdict gate was found to be producing a false positive and was fixed. The
  bytes of the pre-fix gate were never committed. When review asked the obvious
  question -- "prove the new gate does not turn an old NULL into a positive
  finding" -- there was no original to compare against. The author answered by
  RECONSTRUCTING the old gate as ``legacy_derive_verdict()`` and testing the new
  gate against that. Review, correctly, refused: proving a reconstruction correct
  with the reconstruction is circular. The BLOCKER had no answer, because the
  evidence that would have answered it had been destroyed weeks earlier.

WHY THIS RUNS AT EDIT TIME AND NOT AT MERGE TIME
------------------------------------------------
``scripts/check_experiment_artifacts.py`` already DETECTS this after the fact: an
experiment whose entrypoint no longer hashes to the sha its ``reproduce_spec.json``
pins is blocked unless the original bytes sit under ``gate_history/``. That gate is
the enforcement owner for *drift*, and this hook does not duplicate it -- it closes
the one case that gate is structurally unable to remedy.

The difference is whether the bytes are recoverable when the alarm goes off:

  * entrypoint committed, then edited -> merge gate fires, and the fix works:
    ``git show <sha>:experiments/<kid>/<file>`` returns the real original.
    THIS HOOK STAYS SILENT. The bytes are safe; nothing needs interception.
  * entrypoint never committed, then edited -> merge gate fires just the same,
    but its remedy is unrunnable. There is no commit to ``git show``. The only
    copy of those bytes was the working tree, and the edit overwrote it.

The second case is K1708, and it is unfixable after the fact by construction.
So the interception has to happen in the instant before the write, which is the
last moment the evidence still exists. That is this hook, and that is its entire
scope. ``scripts/preserve_gate_blob.py`` names it as the missing "real
interception point" under KNOWN GAP 1.

THE TRIGGER, AND WHY IT IS THIS NARROW
--------------------------------------
A gate with a meaningful false-positive rate gets bypassed rather than obeyed, and
a bypassed gate is worse than none: it teaches people that the alarm means nothing.
So every one of these must hold before the edit is refused:

  1. the target is a ``.py`` file inside ``experiments/<kid>/``
  2. that directory has archived ``*_results.json``       -- there is a published claim
  3. its ``reproduce_spec.json`` declares ``entrypoint.sha256`` and names THIS file
     -- i.e. the spec was machine-generated by ``volpred.research.reproduce_spec``
     at run time, so the sha is trustworthy rather than typed in
  4. the file on disk still hashes to that sha             -- these ARE the bytes that
     produced the archived results; after this write they are not
  5. the file declares verdict/gate logic                  -- the K1708 BLOCKER was
     specifically a before/after gate-behaviour comparison
  6. those bytes are NOT retrievable from git              -- the recoverable case
     belongs to the merge gate, not here (see above)
  7. the sha is not already preserved under ``gate_history/``

Measured against the tree on 2026-07-22: 1,888 ``.py`` files under ``experiments/``,
of which 0 satisfy conditions 2-4 today, because no experiment has adopted the
runtime emitter yet. The hook is a forward ratchet -- it binds the next experiment
that writes results the canonical way, and is inert on the 1,265-experiment backlog.
That inertness is deliberate, not an oversight: synthesising shas for runs nobody
can re-execute is invented history.

ESCAPE HATCH -- deliberately noisy
----------------------------------
``VOLPRED_ALLOW_GATE_EDIT=1`` allows the edit and appends a record to
``storage/ops/gate_edit_overrides.jsonl``. An override that leaves no trace is
indistinguishable from the hook never having fired, which is how a gate quietly
stops existing. Overriding is a legitimate act; overriding *silently* is not.

FAIL-OPEN BY CONSTRUCTION
-------------------------
Any unreadable path, odd payload, missing git, or unexpected error emits ``{}``
(no-op). A hook that breaks Edit costs far more than a hook that occasionally
fails to preserve a blob -- and the merge gate is still downstream of every miss.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import subprocess
import sys
import time
from pathlib import Path

NOOP = "{}"

EDIT_TOOLS = {"Edit", "Write", "MultiEdit", "NotebookEdit"}
SPEC_NAME = "reproduce_spec.json"
SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
OVERRIDE_ENV = "VOLPRED_ALLOW_GATE_EDIT"
OVERRIDE_LOG = Path("storage/ops/gate_edit_overrides.jsonl")

# Deliberately matches DEFINITIONS, not mentions. ``# see derive_verdict`` in a
# comment must not arm the hook; ``def derive_verdict(...)`` must.
GATE_LOGIC_RE = re.compile(
    r"^\s*def\s+\w*(?:verdict|gate)\w*\s*\(",
    re.IGNORECASE | re.MULTILINE,
)


def _noop() -> None:
    print(NOOP)
    raise SystemExit(0)


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _bytes_are_in_git(path: Path) -> bool:
    """True if the file's current content is retrievable from the object store.

    Recoverable bytes are the merge gate's problem, not this hook's: its remedy
    (``git show <sha>:<path>``) works. Only content that exists nowhere but the
    working tree is about to become unrecoverable, and only that is intercepted.

    Returns True on any git failure -- the fail-open direction. Claiming bytes are
    unrecoverable because git did not answer would block an edit on a guess.
    """
    try:
        blob = subprocess.run(
            ["git", "hash-object", "--", str(path)],
            cwd=str(path.parent), capture_output=True, text=True, timeout=10, check=True,
        ).stdout.strip()
        if not blob:
            return True
        probe = subprocess.run(
            ["git", "cat-file", "-e", f"{blob}^{{blob}}"],
            cwd=str(path.parent), capture_output=True, text=True, timeout=10,
        )
        return probe.returncode == 0
    except (OSError, subprocess.SubprocessError):  # silent-ok: documented fail-open hook
        return True


def _preserved_shas(exp_dir: Path) -> set[str]:
    """Shas whose ``gate_history/`` blob is present AND hashes to its claim.

    Re-hashing rather than trusting the manifest: an entry is a claim, the blob is
    the evidence, and passing on a claim is the failure mode this whole mechanism
    exists to reject. Mirrors ``preserve_gate_blob.preserved_shas``; inlined
    because a PreToolUse hook must not depend on repo imports resolving.
    """
    manifest = exp_dir / "gate_history" / "manifest.json"
    try:
        raw = json.loads(manifest.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return set()
    out: set[str] = set()
    for entry in raw.get("entries", []) if isinstance(raw, dict) else []:
        if not isinstance(entry, dict):
            continue
        digest, blob = entry.get("sha256"), entry.get("blob")
        if not isinstance(digest, str) or not isinstance(blob, str):
            continue
        candidate = exp_dir / "gate_history" / Path(blob).name
        try:
            if _sha256(candidate) == digest:
                out.add(digest)
        except OSError:  # silent-ok: an unreadable blob is not preserved evidence
            continue
    return out


def _experiment_dir(path: Path) -> Path | None:
    """``experiments/<kid>`` containing ``path``, or None."""
    parts = path.parts
    try:
        idx = len(parts) - 1 - parts[::-1].index("experiments")
    except ValueError:  # silent-ok: a non-experiment path is outside this hook's scope
        return None
    if idx + 1 >= len(parts):
        return None
    return Path(*parts[: idx + 2])


def evaluate(path: Path) -> tuple[str, dict] | None:
    """``(sha, spec_entrypoint)`` if this edit must be refused, else None.

    Ordered cheapest-first: the overwhelming majority of edits exit at the first
    or second condition without touching git or hashing anything.
    """
    if path.suffix != ".py":
        return None
    exp_dir = _experiment_dir(path)
    if exp_dir is None or not exp_dir.is_dir():
        return None
    if not any(exp_dir.glob("*_results.json")):
        return None

    try:
        spec = json.loads((exp_dir / SPEC_NAME).read_text(encoding="utf-8"))
    except (OSError, ValueError):  # silent-ok: documented fail-open hook
        return None
    if not isinstance(spec, dict):
        return None
    entry = spec.get("entrypoint")
    if not isinstance(entry, dict):
        return None

    declared = entry.get("sha256")
    rel = entry.get("path")
    if not isinstance(declared, str) or not SHA256_RE.match(declared):
        return None  # hand-written pre-convention spec: silence, not a pass claim
    if not isinstance(rel, str):
        return None
    try:
        if (exp_dir / rel).resolve() != path.resolve():
            return None  # not the pinned entrypoint
    except OSError:  # silent-ok: path-resolution failure must not block editing
        return None

    try:
        if _sha256(path) != declared:
            return None  # already drifted; the merge gate owns this, and it is recoverable
        text = path.read_text(encoding="utf-8", errors="ignore")
    except OSError:  # silent-ok: documented fail-open hook
        return None

    if not GATE_LOGIC_RE.search(text):
        return None
    if declared in _preserved_shas(exp_dir):
        return None  # evidence already saved; edit freely
    if _bytes_are_in_git(path):
        return None  # recoverable via git show; merge gate's remedy works

    return declared, {"exp_dir": exp_dir, "rel": rel}


def _record_override(path: Path, sha: str) -> None:
    try:
        log = OVERRIDE_LOG if OVERRIDE_LOG.is_absolute() else Path.cwd() / OVERRIDE_LOG
        log.parent.mkdir(parents=True, exist_ok=True)
        with log.open("a", encoding="utf-8") as fh:
            fh.write(json.dumps({
                "at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                "path": str(path),
                "sha256": sha,
                "override": OVERRIDE_ENV,
            }, ensure_ascii=False) + "\n")
    except OSError:
        pass  # silent-ok: failing to log must never turn an allowed edit into a block


def main() -> None:
    try:
        payload = json.load(sys.stdin)
    except Exception:  # noqa: BLE001
        _noop()

    if payload.get("tool_name") not in EDIT_TOOLS:
        _noop()
    tool_input = payload.get("tool_input") or {}
    raw = tool_input.get("file_path") or tool_input.get("notebook_path")
    if not isinstance(raw, str) or not raw:
        _noop()

    path = Path(raw)
    if not path.is_absolute():
        path = Path.cwd() / path
    if not path.is_file():
        _noop()  # creating a new file destroys nothing

    verdict = evaluate(path)
    if verdict is None:
        _noop()
    sha, info = verdict

    if os.environ.get(OVERRIDE_ENV) == "1":
        _record_override(path, sha)
        print(json.dumps({"hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": "allow",
            "permissionDecisionReason": (
                f"{OVERRIDE_ENV}=1 — gate-blob preservation skipped for {path.name}; "
                f"recorded in {OVERRIDE_LOG}"
            ),
        }}))
        raise SystemExit(0)

    exp_dir: Path = info["exp_dir"]
    rel: str = info["rel"]
    try:
        shown = exp_dir.relative_to(Path.cwd())
    except ValueError:
        shown = exp_dir

    reason = (
        f"{rel} currently holds the exact bytes that produced "
        f"{exp_dir.name}'s archived results (sha {sha[:12]}), those bytes are not in git, "
        f"and it defines verdict/gate logic. Editing now destroys the only copy — and a "
        f"reviewer asking 'does the new gate flip an old NULL?' would have nothing to diff "
        f"against but a reconstruction, which is what got K1708 rejected three rounds "
        f"running. Preserve the original first:\n\n"
        f"  uv run python scripts/preserve_gate_blob.py preserve \\\n"
        f"      --path {shown}/{rel} \\\n"
        f'      --reason "<what the gate change is>"\n\n'
        f"Then re-run this edit. To proceed without preserving (recorded in "
        f"{OVERRIDE_LOG}): {OVERRIDE_ENV}=1"
    )
    print(json.dumps({"hookSpecificOutput": {
        "hookEventName": "PreToolUse",
        "permissionDecision": "deny",
        "permissionDecisionReason": reason,
    }}))


if __name__ == "__main__":
    try:
        main()
    except SystemExit:
        raise
    except Exception:  # noqa: BLE001
        # Never let evidence preservation take Edit down with it.
        print(NOOP)
